### ISSUE TITLE
No module named 'crowd'

### ISSUE THREAD

**Issue by aet239** [pmuller/django-crowd-auth#17]
It seems to be making the API call to Crowd but it cannot find the crowd module
Using: Python3.6
Crowd version 1.0.2 installed in python3.6

**APACHE2 ERROR LOG:**
[Tue Nov 27 08:03:49.765532 2018] [wsgi:error] [pid 536:tid 139772544972544] [remote 36.72.194.34:56044] mod_wsgi (pid=536): Target WSGI script '/var/www/vhosts/harbinger_django/django.wsgi' cannot be loaded as Python module.
[Tue Nov 27 08:03:49.765637 2018] [wsgi:error] [pid 536:tid 139772544972544] [remote 36.72.194.34:56044] mod_wsgi (pid=536): Exception occurred processing WSGI script '/var/www/vhosts/harbinger_django/django.wsgi'.
[Tue Nov 27 08:03:49.765910 2018] [wsgi:error] [pid 536:tid 139772544972544] [remote 36.72.194.34:56044] Traceback (most recent call last):
[Tue Nov 27 08:03:49.766001 2018] [wsgi:error] [pid 536:tid 139772544972544] [remote 36.72.194.34:56044]   File "/var/www/vhosts/harbinger_django/django.wsgi", line 11, in <module>
[Tue Nov 27 08:03:49.766014 2018] [wsgi:error] [pid 536:tid 139772544972544] [remote 36.72.194.34:56044]     application = get_wsgi_application()
[Tue Nov 27 08:03:49.766034 2018] [wsgi:error] [pid 536:tid 139772544972544] [remote 36.72.194.34:56044]   File "/usr/local/lib/python3.6/dist-packages/django/core/wsgi.py", line 13, in get_wsgi_application
[Tue Nov 27 08:03:49.766044 2018] [wsgi:error] [pid 536:tid 139772544972544] [remote 36.72.194.34:56044]     return WSGIHandler()
[Tue Nov 27 08:03:49.766061 2018] [wsgi:error] [pid 536:tid 139772544972544] [remote 36.72.194.34:56044]   File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/wsgi.py", line 136, in __init__
[Tue Nov 27 08:03:49.766071 2018] [wsgi:error] [pid 536:tid 139772544972544] [remote 36.72.194.34:56044]     self.load_middleware()
[Tue Nov 27 08:03:49.766105 2018] [wsgi:error] [pid 536:tid 139772544972544] [remote 36.72.194.34:56044]   File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/base.py", line 34, in load_middleware
[Tue Nov 27 08:03:49.766157 2018] [wsgi:error] [pid 536:tid 139772544972544] [remote 36.72.194.34:56044]     middleware = import_string(middleware_path)
[Tue Nov 27 08:03:49.766183 2018] [wsgi:error] [pid 536:tid 139772544972544] [remote 36.72.194.34:56044]   File "/usr/local/lib/python3.6/dist-packages/django/utils/module_loading.py", line 17, in import_string
[Tue Nov 27 08:03:49.766193 2018] [wsgi:error] [pid 536:tid 139772544972544] [remote 36.72.194.34:56044]     module = import_module(module_path)
[Tue Nov 27 08:03:49.766210 2018] [wsgi:error] [pid 536:tid 139772544972544] [remote 36.72.194.34:56044]   File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
[Tue Nov 27 08:03:49.766220 2018] [wsgi:error] [pid 536:tid 139772544972544] [remote 36.72.194.34:56044]     return _bootstrap._gcd_import(name[level:], package, level)
[Tue Nov 27 08:03:49.766237 2018] [wsgi:error] [pid 536:tid 139772544972544] [remote 36.72.194.34:56044]   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
[Tue Nov 27 08:03:49.766254 2018] [wsgi:error] [pid 536:tid 139772544972544] [remote 36.72.194.34:56044]   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
[Tue Nov 27 08:03:49.766272 2018] [wsgi:error] [pid 536:tid 139772544972544] [remote 36.72.194.34:56044]   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
[Tue Nov 27 08:03:49.766289 2018] [wsgi:error] [pid 536:tid 139772544972544] [remote 36.72.194.34:56044]   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
[Tue Nov 27 08:03:49.766306 2018] [wsgi:error] [pid 536:tid 139772544972544] [remote 36.72.194.34:56044]   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
[Tue Nov 27 08:03:49.766324 2018] [wsgi:error] [pid 536:tid 139772544972544] [remote 36.72.194.34:56044]   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
[Tue Nov 27 08:03:49.766342 2018] [wsgi:error] [pid 536:tid 139772544972544] [remote 36.72.194.34:56044]   File "/usr/local/lib/python3.6/dist-packages/django_crowd_auth/middlewares.py", line 4, in <module>
[Tue Nov 27 08:03:49.766351 2018] [wsgi:error] [pid 536:tid 139772544972544] [remote 36.72.194.34:56044]     from django_crowd_auth.client import Client
[Tue Nov 27 08:03:49.766368 2018] [wsgi:error] [pid 536:tid 139772544972544] [remote 36.72.194.34:56044]   File "/usr/local/lib/python3.6/dist-packages/django_crowd_auth/client.py", line 2, in <module>
[Tue Nov 27 08:03:49.766377 2018] [wsgi:error] [pid 536:tid 139772544972544] [remote 36.72.194.34:56044]     import crowd
[Tue Nov 27 08:03:49.766410 2018] [wsgi:error] [pid 536:tid 139772544972544] [remote 36.72.194.34:56044] ModuleNotFoundError: No module named 'crowd'

**Contents of settings.py:**
INSTALLED_APPS = [
    'django_crowd_auth',
    'harbinger.apps.HarbingerConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bootstrap3',
    'bootstrap_themes',
    'jquery',
]
CROWD_CLIENT = {
        'crowd_url': 'http://notprovided.notprovided.net:8095/crowd',
                'app_name': 'notprovided',
                'app_pass': 'notprovided!',
                'timeout': 10,
                }
CROWD_USERS_ARE_STAFF = True
CROWD_SUPERUSERS_GROUP = 'administrators'
AUTHENTICATION_BACKENDS = ['django_crowd_auth.backends.Backend']
MIDDLEWARE = [
#    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django_crowd_auth.middlewares.sso',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
   # 'crowd.middlewares.CrowdMiddleware',
]

**Comment by pmuller** [comment]
django-crowd-auth depends on the [Crowd package](https://pypi.org/project/Crowd/) (as specified in [setup.py](https://github.com/pmuller/django-crowd-auth/blob/master/setup.py#L32)).

Reading the stacktrace, it seems it is not installed on your system. Could you check ?
